src/Entity/Activity.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ActivityRepository")
 * @Vich\Uploadable
 * @UniqueEntity(
 *     fields = {"name"},
 *     message = "Ce nom d'activité existe déjà !"
 * )
 */
class Activity
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $name;


    /**
     * @var string|null
     * @ORM\column(type="string", length=255, nullable=true)
     */
    private $fileName;

    /**
     * @Vich\UploadableField(mapping="activity_image", fileNameProperty="fileName")
     * @var File|null
     */
    private $imageFile;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\UserActivity", mappedBy="activity_id", cascade={"persist", "remove"})
     */
    private $userActivities;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Questions", mappedBy="activity", cascade={"persist", "remove"})
     */
    private $question;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="activity_creator")
     * @ORM\JoinColumn(nullable=false)
     */
    private $created_by;

    /**
     * @ORM\Column(type="boolean")
     */
    private $visible;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\QuestionsGroupes", mappedBy="activity", cascade={"persist", "remove"})
     */
    private $questionsGroupes;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\ActivityType", inversedBy="activity")
     * @ORM\JoinColumn(nullable=false)
     */
    private $type;

    public function __construct()
    {
        $this->userActivities = new ArrayCollection();
        $this->question = new ArrayCollection();
        $this->questionsGroupes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return null|string
     */
    public function getFileName(): ?string
    {
        return $this->fileName;
    }

    /**
     * @param null|string $fileName
     * @return Questions
     */
    public function setFileName(?string $fileName): Activity
    {
        $this->fileName = $fileName;
        return $this;
    }

    /**
     * @return null|File
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param null|File $imageFile
     * @return Questions
     */
    public function setImageFile(?File $imageFile): Activity
    {
        $this->imageFile = $imageFile;
        if ($this->imageFile instanceof UploadedFile) {
            $this->updated_at = new \DateTime('now');
        }
        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection|UserActivity[]
     */
    public function getUserActivities(): Collection
    {
        return $this->userActivities;
    }

    public function addUserActivity(UserActivity $userActivity): self
    {
        if (!$this->userActivities->contains($userActivity)) {
            $this->userActivities[] = $userActivity;
            $userActivity->setActivityId($this);
        }

        return $this;
    }

    public function removeUserActivity(UserActivity $userActivity): self
    {
        if ($this->userActivities->contains($userActivity)) {
            $this->userActivities->removeElement($userActivity);
            // set the owning side to null (unless already changed)
            if ($userActivity->getActivityId() === $this) {
                $userActivity->setActivityId(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Questions[]
     */
    public function getQuestion(): Collection
    {
        return $this->question;
    }

    public function addQuestion(Questions $question): self
    {
        if (!$this->question->contains($question)) {
            $this->question[] = $question;
            $question->setActivity($this);
        }

        return $this;
    }

    public function removeQuestion(Questions $question): self
    {
        if ($this->question->contains($question)) {
            $this->question->removeElement($question);
            // set the owning side to null (unless already changed)
            if ($question->getActivity() === $this) {
                $question->setActivity(null);
            }
        }

        return $this;
    }

    public function getCreatedBy(): ?User
    {
        return $this->created_by;
    }

    public function setCreatedBy(?User $created_by): self
    {
        $this->created_by = $created_by;

        return $this;
    }

    public function getVisible(): ?bool
    {
        return $this->visible;
    }

    public function setVisible(bool $visible): self
    {
        $this->visible = $visible;

        return $this;
    }

    /**
     * @return Collection|QuestionsGroupes[]
     */
    public function getQuestionsGroupes(): Collection
    {
        return $this->questionsGroupes;
    }

    public function addQuestionsGroupe(QuestionsGroupes $questionsGroupe): self
    {
        if (!$this->questionsGroupes->contains($questionsGroupe)) {
            $this->questionsGroupes[] = $questionsGroupe;
            $questionsGroupe->setActivity($this);
        }

        return $this;
    }

    public function removeQuestionsGroupe(QuestionsGroupes $questionsGroupe): self
    {
        if ($this->questionsGroupes->contains($questionsGroupe)) {
            $this->questionsGroupes->removeElement($questionsGroupe);
            // set the owning side to null (unless already changed)
            if ($questionsGroupe->getActivity() === $this) {
                $questionsGroupe->setActivity(null);
            }
        }

        return $this;
    }

    public function getType(): ?ActivityType
    {
        return $this->type;
    }

    public function setType(?ActivityType $type): self
    {
        $this->type = $type;

        return $this;
    }
}

src/Entity/ActivityType.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ActivityTypeRepository")
 */
class ActivityType
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Activity", mappedBy="type")
     */
    private $activity;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\CSV", mappedBy="type")
     */
    private $cSVs;

    public function __construct()
    {
        $this->activity = new ArrayCollection();
        $this->cSVs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|Activity[]
     */
    public function getActivity(): Collection
    {
        return $this->activity;
    }

    public function addActivity(Activity $activity): self
    {
        if (!$this->activity->contains($activity)) {
            $this->activity[] = $activity;
            $activity->setType($this);
        }

        return $this;
    }

    public function removeActivity(Activity $activity): self
    {
        if ($this->activity->contains($activity)) {
            $this->activity->removeElement($activity);
            // set the owning side to null (unless already changed)
            if ($activity->getType() === $this) {
                $activity->setType(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|CSV[]
     */
    public function getCSVs(): Collection
    {
        return $this->cSVs;
    }

    public function addCSV(CSV $cSV): self
    {
        if (!$this->cSVs->contains($cSV)) {
            $this->cSVs[] = $cSV;
            $cSV->setType($this);
        }

        return $this;
    }

    public function removeCSV(CSV $cSV): self
    {
        if ($this->cSVs->contains($cSV)) {
            $this->cSVs->removeElement($cSV);
            // set the owning side to null (unless already changed)
            if ($cSV->getType() === $this) {
                $cSV->setType(null);
            }
        }

        return $this;
    }
}

src/Form/ActivityType.php
<?php

namespace App\Form;

use App\Entity\Activity;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ActivityType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('imageFile', FileType::class, [
                'required' => false
            ])
            ->add('visible', CheckboxType::class, [
                'required' => false
            ])
            ->add('type', EntityType::class, [
                'class' => \App\Entity\ActivityType::class,
                'choice_label' => 'name'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Activity::class,
        ]);
    }
}

src/Controller/ActivityController.php
<?php

namespace App\Controller;


use App\Entity\Activity;
use App\Entity\ActivitySearch;
use App\Entity\UserActivity;
use App\Form\ActivitySearchType;
use App\Form\ActivityType;
use App\Repository\ActivityRepository;
use App\Repository\QuestionsRepository;
use App\Repository\UserActivityRepository;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ActivityController extends AbstractController
{
    /**
     * @Route("/activity", name="activity")
     * @param ActivityRepository $activityRepository
     * @param Request $request
     * @return Response
     */
    public function showActivities(ActivityRepository $activityRepository, Request $request)
    {
        $search = new ActivitySearch();
        $form = $this->createForm(ActivitySearchType::class, $search);
        $form->handleRequest($request);
        $activities = $activityRepository->findActivitySearch($search);

        return $this->render('activity/index.html.twig', [
            'activites' => $activities,
            'current_menu' => 'activity',
            'perso' => false,
            'form_activity' => $form->createView()
        ]);
    }

    /**
     * @param ActivityRepository $activityRepository
     * @return Response
     * @Route("/activity/perso", name="activityPerso")
     */
    public function showTeacherActivities(ActivityRepository $activityRepository){

        $activities = $activityRepository->findBy(['created_by' => $this->getUser()]);

        return $this->render('activity/index.html.twig', [
            'activites' => $activities,
            'current_menu' => 'activity',
            'perso' => true
        ]);
    }

    /**
     * @Route("/activity/new", name="new_activity")
     * @Route("/activity/{id}/edit", name="edit_activity")
     * @param null $id
     * @param Activity|null $activity
     * @param Request $request
     * @param ObjectManager $manager
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
     */
    public function create($id = null, Activity $activity = null, Request $request, ObjectManager $manager){

        if(!$activity){
            $activity = new Activity();
        }

        $form = $this->createForm(ActivityType::class, $activity);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){

            $activity->setCreatedBy($this->getUser());

            $manager->persist($activity);

            $manager->flush();

            if(!$id){
                return $this->redirectToRoute('activity_'. $activity->getType()->getName() .'_new', ['id' => $activity->getId()]);
            }else {
                $this->addFlash('success', 'Activité modifiée avec succès');
                return $this->redirectToRoute('activity_' . $activity->getType()->getName(), ['id' => $activity->getId()]);
            }


        }



        return $this->render('activity/new.html.twig', [
                'form_act' => $form->createView(),
                'activity' => $activity
        ]);
    }

    /**
     * @Route("{id}/verification/qcm", name="verification_qcm")
     * @param $id
     * @param Request $request
     * @param QuestionsRepository $questionRepository
     * @param UserActivityRepository $userActivityRepository
     * @param ObjectManager $manager
     * @return Response
     */
    public function verification($id, Request $request, QuestionsRepository $questionRepository, UserActivityRepository $userActivityRepository, ObjectManager $manager){

        $point = 0;
        $total = 0;
        $questionPrecedente = '';
        $tab = $request->request->all();

        $user_activity = $userActivityRepository->findOneby(['user_id' => $this->getUser(), 'activity_id' => $id]);

        while ($reponse = current($tab)){

            $questionIS = str_replace("_", " ", substr(key($tab), 2 ));//je récupère la question
            $question = $questionRepository->findOneBy(['question' => $questionIS]);//je vais chercher les bonnes réponses liées à la question

            if($questionIS == $questionPrecedente){
                $idem = true;
            }else {
                $idem = false;
            }

            if($idem == false){
                $total = $total + $question->getPoints();
            }

            if(in_array($reponse, [$question->getBonneReponse1(), $question->getBonneReponse2(), $question->getBonneReponse3()])){
                $point++;
            }else {
                $point = $point-0.2;
            }
            next($tab);
            $questionPrecedente = $questionIS;
        }

        $user_activity->setPoint($point);
        $user_activity->setTotal($total);

        $manager->persist($user_activity);
        $manager->flush();

        return $this->render('activity/retour.html.twig', [
            'point' => $point,
            'total' => $total,
            'id' => $id
        ]);
    }

    /**
     * @param Activity $activity
     * @param ObjectManager $manager
     * @Route("/activity/{id}/delete", name="activity_delete")
     */
    public function delete($id, ActivityRepository $activityRepository, ObjectManager $manager){

        $activities = $activityRepository->findOneby(['id' => $id]);
        $manager->remove($activities);
        $manager->flush();
        return $this->redirectToRoute('activityPerso');
    }
}

templates/activity/activity.html.twig
{% extends 'base.html.twig' %}

{% block title %}Activité QCM{% endblock %}

{% block body %}


    <div class="jumbotron">
        <h1>{{ activities.name }}</h1>
        {% for message in app.flashes('success') %}
            <div class="alert alert-success">
                {{ message }}
            </div>
        {% endfor %}
    </div>
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-lg-7 col-md-7">
                <form action="{{ path('verification_qcm', {'id' : activities.id}) }}" method="post">
                    {% for question in activities.question %}
                        {% if is_granted('ROLE_PROFESSEUR') %}
                            <a href="{{ path('activity_questions_edit', {'id' : activities.id, 'slug' : question.id}) }}" class="btn btn-secondary">Modifier</a>
                            <a href="{{ path('activity_question_delete', {'id' : activities.id, 'slug' : question.id}) }}" class="btn btn-danger">Supprimer</a>
                        {% endif %}
                        <h2>{{ question.question }}</h2>
                        {% if question.fileName %}
                            <img src="{{ vich_uploader_asset(question, 'imageFile') }}" alt="card-question" style="width: 80%; height: auto;">
                        {% endif %}

                        <div class="col-6 col-lg-6 col-md-6">
                        {% for test in tab | shuffle() %}
                            {% if test == 'question.bonneReponse1' %}
                                {% if (question.bonneReponse1) %}
                                    <div class="form-check p-2">
                                        <label class="form-check-label">
                                            <input class="form-check-label" type="checkbox" name="{{ '0:'~question.question }}" value="{{ question.bonneReponse1 }}">{{ question.bonneReponse1 }}<br>
                                        </label>
                                    </div>
                                {% endif %}
                            {% elseif test == 'question.bonneReponse2' %}
                                {% if (question.bonneReponse2) %}
                                    <div class="form-check p-2">
                                        <label class="form-check-label">
                                            <input type="checkbox" name="{{ '1:'~question.question }}" value="{{ question.bonneReponse2 }}">{{ question.bonneReponse2 }}
                                        </label>
                                    </div>
                                {% endif %}
                            {% elseif test == 'question.bonneReponse3' %}
                                {% if (question.bonneReponse3) %}
                                    <div class="form-check p-2">
                                        <label class="form-check-label">
                                            <input type="checkbox" name="{{ '2:'~question.question }}" value="{{ question.bonneReponse3 }}">{{ question.bonneReponse3 }}<br>
                                        </label>
                                    </div>
                                {% endif %}
                            {% elseif test == 'question.mauvaiseReponse1' %}
                                {% if (question.mauvaiseReponse1) %}
                                    <div class="form-check p-2">
                                        <label class="form-check-label">
                                            <input type="checkbox" name="{{ '3:'~question.question }}" value="{{ question.mauvaiseReponse1 }}">{{ question.mauvaiseReponse1 }}<br>
                                        </label>
                                    </div>
                                {% endif %}
                            {% elseif test == 'question.mauvaiseReponse2' %}
                                {% if (question.mauvaiseReponse2) %}
                                    <div class="form-check p-2">
                                        <label class="form-check-label">
                                            <input type="checkbox" name="{{ '4:'~question.question }}" value="{{ question.mauvaiseReponse2 }}">{{ question.mauvaiseReponse2 }}<br>
                                        </label>
                                    </div>
                                {% endif %}
                            {% elseif test == 'question.mauvaiseReponse3' %}
                                {% if (question.mauvaiseReponse3) %}
                                    <div class="form-check p-2">
                                        <label class="form-check-label">
                                            <input type="checkbox" name="{{ '5:'~question.question }}" value="{{ question.mauvaiseReponse3 }}">{{ question.mauvaiseReponse3 }}<br>
                                        </label>
                                    </div>
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                        </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-success m-1">Envoyer vos réponses</button>

                </form>

                {% if is_granted('ROLE_PROFESSEUR') %}
                    <a href="{{ path('activity_questions_new', {'id' : activities.id}) }}" class="btn btn-info m-1">Ajouter une question</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/activity/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Activités{% endblock %}

{% block body %}

    <div class="jumbotron flex">
        <h1 class="d-inline">Activités</h1>
        {% if is_granted('ROLE_PROFESSEUR') %}
            <a href="{{ path('new_activity') }}" class="btn btn-primary pull-right">Créer une activité</a>
        {% endif %}
        {% for message in app.flashes('error') %}
            <div class="alert alert-danger">
                {{ message }}
            </div>
        {% endfor %}
    </div>

    <div class="m-3">
        <div class="row flex">

            {% for activite in activites %}
                <div class="col-xs-4 col-lg-4 col-md-4 mb-3" >
                        <div class="card h-100">
                            {% if activite.fileName %}
                                <img class="card-img-top" src="{{ vich_uploader_asset(activite, 'imageFile') }}" alt="Card image cap" style="width: 100%; height: auto">
                            {% else %}
                                <img class="card-img-top mt-5 mb-5" src="/images/activity/activity.png" alt="Card image cap" style="width: 100%; height: auto">
                            {% endif %}
                            <div class="card-body text-center">
                                <h3 class="card-title mb-3">{{ activite.name }}</h3>
                                <div class="text-center">
                                <a href="{{ path('activity_questions', {'id': activite.id}) }}" class="btn btn-primary">Effectuer</a>
                                    {% if is_granted('ROLE_PROFESSEUR') and app.user.id == activite.createdBy.id %}
                                        <a href="{{ path('edit_activity', {'id' : activite.id}) }}" class="btn btn-warning m-1">Modifier l'activité</a>
                                        <a href="{{ path('activity_delete', {'id': activite.id}) }}" class="btn btn-danger">Supprimer</a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/activity/new.html.twig
{% extends 'base.html.twig' %}

{% form_theme form_act 'bootstrap_4_layout.html.twig' %}

{% block title %}Activité{% endblock %}

{% block body %}

    <div class="jumbotron">
        <h1>Création d'une activité</h1>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-7 col-md-7">


                {{ form_start(form_act) }}

                {{ form_row(form_act.name, {
                    'attr' : {
                        'placeholder' : "Quelle est le nom de l'activité (obligatoire)"
                    },
                    'label' : 'Nom de l\'activité'
                }) }}

                {{ form_row(form_act.imageFile, {
                    'attr' : {
                        'placeholder' : "Ajouter une image (facultative)"
                    },
                    'label' : 'Image pour l\'activité'
                }) }}

                {{ form_row(form_act.visible, {
                    'attr' : {
                        'placeholder' : "Activité visible dans la liste"
                    }
                }) }}

                <button type="submit" class="btn btn-success">{% if(activity.id) %}Appliquer les modifications{% else %}Ajouter des questions{% endif %}</button>

                {{ form_end(form_act) }}
            </div>
        </div>
    </div>





{% endblock %}

templates/activity/retour.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello{% endblock %}

{% block body %}
    <h1>Tu as obtenu {{ point }} sur {{ total }}</h1>

    {% if point < total/2 %}
        <p>N'hésitez pas à la recommencer <a href="{{ path('activity_questions', {'id' : id}) }}">Clique ici</a></p>
    {% endif %}
{% endblock %}