src/Entity/UserActivity.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserActivityRepository")
 */
class UserActivity
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="activity_id")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user_id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Activity", inversedBy="userActivities")
     * @ORM\JoinColumn(nullable=false)
     */
    private $activity_id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $point;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $total;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserId(): ?User
    {
        return $this->user_id;
    }

    public function setUserId(?User $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getActivityId(): ?Activity
    {
        return $this->activity_id;
    }

    public function setActivityId(?Activity $activity_id): self
    {
        $this->activity_id = $activity_id;

        return $this;
    }

    public function getPoint(): ?string
    {
        return $this->point;
    }

    public function setPoint(string $point): self
    {
        $this->point = $point;

        return $this;
    }

    public function getTotal(): ?string
    {
        return $this->total;
    }

    public function setTotal(string $total): self
    {
        $this->total = $total;

        return $this;
    }
}

src/Controller/ResultatController.php
<?php

namespace App\Controller;

use App\Entity\ResultSearch;
use App\Form\ResultSearchType;
use App\Repository\UserActivityRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class ResultatController extends AbstractController
{
    /**
     * @Route("/resultats", name="resultat")
     */
    public function index(UserActivityRepository $userActivityRepository, Request $request)
    {

        $search = new ResultSearch();
        $form = $this->createForm(ResultSearchType::class, $search);
        $form->handleRequest($request);
        $user_activity = $userActivityRepository->findAllVisibleQuery($search);
        //$user_activity = $userActivityRepository->findAll();
        //$user_activity = $userActivityRepository->myFind(31);

        return $this->render('resultat/index.html.twig', [
            'user_activity' => $user_activity,
            'form_result' => $form->createView()
        ]);
    }

    /**
     * @param UserActivityRepository $userActivityRepository
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     * @Route("/points/{id}", name="resultatPerso")
     */
    public function resultatPerso($id = null, UserActivityRepository $userActivityRepository, Request $request){

        $search = new ResultSearch();
        $form = $this->createForm(ResultSearchType::class, $search);
        $form->handleRequest($request);
        $user_activity = $userActivityRepository->findBy(['user_id' => $id]);

        return $this->render('resultat/index.html.twig', [
            'user_activity' => $user_activity,
            'form_result' => $form->createView()
        ]);
    }
}

templates/resultat/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Resultats{% endblock %}

{% block body %}
    <div class="jumbotron">
        {% if is_granted('ROLE_PROFESSEUR') %}
            <h1>Résultats élèves</h1>
        {% else %}
            <h1>Vos résultats</h1>
        {% endif %}
        {% if is_granted('ROLE_PROFESSEUR') %}
        <div class="container">
            {{ form_start(form_result) }}
            <div class="form-row">
                <div class="col-12 col-sm-3 col-md-3 col-lg-3">
                    {{ form_row(form_result.classe) }}
                </div>
                <div class="col-12 col-sm-4 col-md-4 col-lg-4">
                    {{ form_row(form_result.matiere) }}
                </div>
                <div class="col-12 col-sm-4 col-md-4 col-lg-4">
                    <button class="btn btn-primary">Rechercher</button>
                </div>
            </div>
            {{ form_end(form_result) }}
        </div>
        {% endif %}
    </div>

    <div class="container">
        <div class="row">
            <div class="col-12 col-lg-9 col-md-11">
                <table id="tableResultat" class="table table-striped table-responsive">
                    <thead>
                        <tr>
                            {% if is_granted('ROLE_PROFESSEUR') %}
                            <th scope="col">Nom</th>
                            <th scope="col">Prénom</th>
                            <th scope="col">Classe</th>
                            {% endif %}
                            <th scope="col">Activité</th>
                            <th scope="col">Point</th>
                            <th scope="col">Total</th>
                        </tr>
                    </thead>
                    <tbody>
                {% for result in user_activity %}
                    <tr>
                        {% if is_granted('ROLE_PROFESSEUR') %}
                        <td>{{ result.userId.nom }}</td>
                        <td>{{ result.userId.prenom }}</td>
                        {% for classe in result.userId.classes %}
                            <td>{{ classe.nom }}</td>
                        {% endfor %}
                        {% endif %}
                        <td>{{ result.activityId.name }}</td>
                        <td>{{ result.point }}</td>
                        {#Permet de recalculer le total de l'activité#}
                        {% set total = 0 %}
                        {% for question in result.activityId.question %}
                            {% set total = total + question.points %}
                        {% endfor %}
                        <td>{{ total }}</td>
                    </tr>
                {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}